### PR TITLE
Fix: update dependency packages

### LINKED ISSUE #17: failed to decode: CycloneDX
We use trivy 0.44.1 with referrer 0.2.0 with this command : 

`trivy image -q -f cyclonedx $IMAGE_SRC | trivy referrer put`

but we receive this error message : 

`Error: error putting referrer: error getting referrer: error processing SBOM: error decoding SBOM: failed to decode: CycloneDX decode error: invalid specification version`

any idea ?

### PR DESCRIPTION
**Pull request by otms61**
Fix https://github.com/aquasecurity/trivy-plugin-referrer/issues/17

This PR addresses the following updates:

- Support for CycloneDX v1.5： [Release Notes](https://github.com/CycloneDX/cyclonedx-go/releases/tag/v0.7.2)
- Handling breaking changes in the type of `remote.Referrers`: [Related PR](https://github.com/google/go-containerregistry/pull/1652)
- Adaptation to data type changes in SPDX: [Release Notes](https://github.com/spdx/tools-golang/releases/tag/v0.5.0)

In the latest commit, functionality has been checked using the following command.

```console
$ trivy_0.42.1 image -q -f cyclonedx   localhost:5002/demo4:app | ./trivy-plugin-referrer put
2023-09-01T00:29:39.965+0900	WARN	Ignore the OS package as no OS information is found.
2023-09-01T00:29:39.965+0900	INFO	SBOM detected: cyclonedx-json
2023-09-01T00:29:40.012+0900	INFO	Pushing referrer to localhost:5002/demo4@sha256:9a21287212ce36b6ee0eeeea2450390120416bfcd0dd29dddcd3182494bbf1ab

$ trivy_0.44.1 image -q -f cyclonedx   localhost:5002/demo4:app | ./trivy-plugin-referrer put
2023-09-01T00:29:47.815+0900	WARN	Ignore the OS package as no OS information is found.
2023-09-01T00:29:47.815+0900	INFO	SBOM detected: cyclonedx-json
2023-09-01T00:29:47.860+0900	INFO	Pushing referrer to localhost:5002/demo4@sha256:c59fcee6d003f61a1782f44b210b7a9c2950715891948bf443da2b231cf246f0

$ trivy_0.42.1 image -q -f spdx-json  localhost:5002/demo4:app | ./trivy-plugin-referrer put
2023-09-01T00:29:54.154+0900	INFO	SBOM detected: spdx-json
2023-09-01T00:29:54.186+0900	INFO	Pushing referrer to localhost:5002/demo4@sha256:d9e277a527d80f96b5e25a233dddc38164e012e365d196655ab63405ab533b66

$ trivy_0.44.1 image -q -f spdx-json  localhost:5002/demo4:app | ./trivy-plugin-referrer put
2023-09-01T00:30:05.637+0900	INFO	SBOM detected: spdx-json
2023-09-01T00:30:05.681+0900	INFO	Pushing referrer to localhost:5002/demo4@sha256:43eafc79781c8452eaa5ae1c94a6b23cd27a3fd9b04e8faefa0b6b4e9134fec8
```

### CODE REVIEW

File: list.go [hunk 1]
```diff
@@ -253,16 +252,14 @@ func listReferrers(writer io.Writer, opts listOptions) error {
...
+	if err != nil {
+		return fmt.Errorf("error fetching referrers: %w", err)
+	}
 
+	index, err := imageIndex.IndexManifest()
 	if err != nil {
-		if e, ok := err.(*transport.Error); ok && e.StatusCode == 404 {
-			// If the OCI registry returns 404, process it as an index with no referrer. This happens when the OCI registry does not support
-			// the referrers API.
-			index = &v1.IndexManifest{}
```
Comment (otms61) [inline list.go:262]: This code was originally implemented to avoid a past bug, and is no longer necessary.
The original API now returns an empty IndexManifest as well.

This issue has been fixed in this [PR](https://github.com/google/go-containerregistry/pull/1648).

File: tree.go [hunk 2]
```diff
@@ -48,17 +47,17 @@ func treeReferrers(w io.Writer, opts treeOptions) error {
...
 func recurseReferrers(node treeprint.Tree, digest name.Digest) error {
-	index, err := remote.Referrers(digest, remote.WithAuthFromKeychain(authn.DefaultKeychain))
+	imageIndex, err := remote.Referrers(digest, remote.WithAuthFromKeychain(authn.DefaultKeychain))
 
 	if err != nil {
-		if e, ok := err.(*transport.Error); ok && e.StatusCode == 404 {
-			// If the OCI registry returns 404, process it as an index with no referrer. This happens when the OCI registry does not support
-			// the referrers API.
-			return nil
-		}
```
Comment (otms61) [inline tree.go:58]: The issue has been resolved in the same PR as mentioned above: [Related PR](https://github.com/google/go-containerregistry/pull/1648)

This code was originally implemented to avoid a past bug, and is no longer necessary.
The original API now returns an empty IndexManifest as well.

**Review by knqyf263 — APPROVED** [review]
